apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth-test
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::64e54544:role/eksctl-my-cluster-nodegroup-standard-wo-NodeInstanceRole-1WP3NUE3O6UCF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: <arn:aws:iam::64e54544:user/admin>
      username: <admin>
      groups:
        - <system:masters>
    - userarn: <arn:aws:iam::64e54544:user/ops-user>
      username: <ops-user>
      groups:
        - <system:masters>
