/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	"context"
	"time"

	v1beta "github.com/vegito11/AWSAuthSync/pkg/apis/vegito11.io/v1beta"
	scheme "github.com/vegito11/AWSAuthSync/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AWSAuthMapsGetter has a method to return a AWSAuthMapInterface.
// A group's client should implement this interface.
type AWSAuthMapsGetter interface {
	AWSAuthMaps(namespace string) AWSAuthMapInterface
}

// AWSAuthMapInterface has methods to work with AWSAuthMap resources.
type AWSAuthMapInterface interface {
	Create(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.CreateOptions) (*v1beta.AWSAuthMap, error)
	Update(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.UpdateOptions) (*v1beta.AWSAuthMap, error)
	UpdateStatus(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.UpdateOptions) (*v1beta.AWSAuthMap, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta.AWSAuthMap, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta.AWSAuthMapList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta.AWSAuthMap, err error)
	AWSAuthMapExpansion
}

// aWSAuthMaps implements AWSAuthMapInterface
type aWSAuthMaps struct {
	client rest.Interface
	ns     string
}

// newAWSAuthMaps returns a AWSAuthMaps
func newAWSAuthMaps(c *Vegito11V1betaClient, namespace string) *aWSAuthMaps {
	return &aWSAuthMaps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aWSAuthMap, and returns the corresponding aWSAuthMap object, and an error if there is any.
func (c *aWSAuthMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta.AWSAuthMap, err error) {
	result = &v1beta.AWSAuthMap{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsauthmaps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AWSAuthMaps that match those selectors.
func (c *aWSAuthMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta.AWSAuthMapList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta.AWSAuthMapList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsauthmaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aWSAuthMaps.
func (c *aWSAuthMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsauthmaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aWSAuthMap and creates it.  Returns the server's representation of the aWSAuthMap, and an error, if there is any.
func (c *aWSAuthMaps) Create(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.CreateOptions) (result *v1beta.AWSAuthMap, err error) {
	result = &v1beta.AWSAuthMap{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsauthmaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aWSAuthMap).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aWSAuthMap and updates it. Returns the server's representation of the aWSAuthMap, and an error, if there is any.
func (c *aWSAuthMaps) Update(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.UpdateOptions) (result *v1beta.AWSAuthMap, err error) {
	result = &v1beta.AWSAuthMap{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsauthmaps").
		Name(aWSAuthMap.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aWSAuthMap).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aWSAuthMaps) UpdateStatus(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.UpdateOptions) (result *v1beta.AWSAuthMap, err error) {
	result = &v1beta.AWSAuthMap{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsauthmaps").
		Name(aWSAuthMap.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aWSAuthMap).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aWSAuthMap and deletes it. Returns an error if one occurs.
func (c *aWSAuthMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsauthmaps").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aWSAuthMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsauthmaps").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aWSAuthMap.
func (c *aWSAuthMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta.AWSAuthMap, err error) {
	result = &v1beta.AWSAuthMap{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsauthmaps").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
