/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta "github.com/vegito11/AWSAuthSync/pkg/apis/vegito11.io/v1beta"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAWSAuthMaps implements AWSAuthMapInterface
type FakeAWSAuthMaps struct {
	Fake *FakeVegito11V1beta
	ns   string
}

var awsauthmapsResource = schema.GroupVersionResource{Group: "vegito11.io", Version: "v1beta", Resource: "awsauthmaps"}

var awsauthmapsKind = schema.GroupVersionKind{Group: "vegito11.io", Version: "v1beta", Kind: "AWSAuthMap"}

// Get takes name of the aWSAuthMap, and returns the corresponding aWSAuthMap object, and an error if there is any.
func (c *FakeAWSAuthMaps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta.AWSAuthMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awsauthmapsResource, c.ns, name), &v1beta.AWSAuthMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.AWSAuthMap), err
}

// List takes label and field selectors, and returns the list of AWSAuthMaps that match those selectors.
func (c *FakeAWSAuthMaps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta.AWSAuthMapList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awsauthmapsResource, awsauthmapsKind, c.ns, opts), &v1beta.AWSAuthMapList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta.AWSAuthMapList{ListMeta: obj.(*v1beta.AWSAuthMapList).ListMeta}
	for _, item := range obj.(*v1beta.AWSAuthMapList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aWSAuthMaps.
func (c *FakeAWSAuthMaps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awsauthmapsResource, c.ns, opts))

}

// Create takes the representation of a aWSAuthMap and creates it.  Returns the server's representation of the aWSAuthMap, and an error, if there is any.
func (c *FakeAWSAuthMaps) Create(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.CreateOptions) (result *v1beta.AWSAuthMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awsauthmapsResource, c.ns, aWSAuthMap), &v1beta.AWSAuthMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.AWSAuthMap), err
}

// Update takes the representation of a aWSAuthMap and updates it. Returns the server's representation of the aWSAuthMap, and an error, if there is any.
func (c *FakeAWSAuthMaps) Update(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.UpdateOptions) (result *v1beta.AWSAuthMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awsauthmapsResource, c.ns, aWSAuthMap), &v1beta.AWSAuthMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.AWSAuthMap), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAWSAuthMaps) UpdateStatus(ctx context.Context, aWSAuthMap *v1beta.AWSAuthMap, opts v1.UpdateOptions) (*v1beta.AWSAuthMap, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(awsauthmapsResource, "status", c.ns, aWSAuthMap), &v1beta.AWSAuthMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.AWSAuthMap), err
}

// Delete takes name of the aWSAuthMap and deletes it. Returns an error if one occurs.
func (c *FakeAWSAuthMaps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(awsauthmapsResource, c.ns, name, opts), &v1beta.AWSAuthMap{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAWSAuthMaps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awsauthmapsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta.AWSAuthMapList{})
	return err
}

// Patch applies the patch and returns the patched aWSAuthMap.
func (c *FakeAWSAuthMaps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta.AWSAuthMap, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awsauthmapsResource, c.ns, name, pt, data, subresources...), &v1beta.AWSAuthMap{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.AWSAuthMap), err
}
