/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta

import (
	"context"
	time "time"

	vegito11iov1beta "github.com/vegito11/AWSAuthSync/pkg/apis/vegito11.io/v1beta"
	versioned "github.com/vegito11/AWSAuthSync/pkg/client/clientset/versioned"
	internalinterfaces "github.com/vegito11/AWSAuthSync/pkg/client/informers/externalversions/internalinterfaces"
	v1beta "github.com/vegito11/AWSAuthSync/pkg/client/listers/vegito11.io/v1beta"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AWSAuthMapInformer provides access to a shared informer and lister for
// AWSAuthMaps.
type AWSAuthMapInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta.AWSAuthMapLister
}

type aWSAuthMapInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAWSAuthMapInformer constructs a new informer for AWSAuthMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAWSAuthMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAWSAuthMapInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAWSAuthMapInformer constructs a new informer for AWSAuthMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAWSAuthMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Vegito11V1beta().AWSAuthMaps(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Vegito11V1beta().AWSAuthMaps(namespace).Watch(context.TODO(), options)
			},
		},
		&vegito11iov1beta.AWSAuthMap{},
		resyncPeriod,
		indexers,
	)
}

func (f *aWSAuthMapInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAWSAuthMapInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aWSAuthMapInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vegito11iov1beta.AWSAuthMap{}, f.defaultInformer)
}

func (f *aWSAuthMapInformer) Lister() v1beta.AWSAuthMapLister {
	return v1beta.NewAWSAuthMapLister(f.Informer().GetIndexer())
}
